version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: DEVDatabase
      MYSQL_USER: padmin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

